# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 898cf21ad3cfec770083570caff239681d8996ee4e6ce109de48ad36c9753dde965a6ca6335de345c9ab20bd43233f482a4852e1fafc0ed1219b592547954253

test:
  secret_key_base: 2fde7f5c1b40926e90b0ff7ceaf14e8e08850d2806810d070117b53033cb10e6560d26952d2e80d9179d735b1696e9f7118db17c82d5fb340521ee174aa4588d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
